# Generated by Django 2.2 on 2020-03-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookadd',
            name='availability',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bookadd',
            name='isbno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bookadd',
            name='pageno',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
