# Generated by Django 2.2 on 2020-03-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givebook', '0002_auto_20200330_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookadd',
            name='availability',
            field=models.IntegerField(default=1),
        ),
    ]
