# Generated by Django 2.2 on 2020-03-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givebook', '0003_auto_20200330_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookadd',
            name='reqid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
