# Generated by Django 2.2 on 2020-03-31 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givebook', '0004_bookadd_reqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookadd',
            name='reqid',
            field=models.IntegerField(null=True),
        ),
    ]
