# Generated by Django 2.2 on 2020-03-31 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givebook', '0005_auto_20200331_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookadd',
            name='pageno',
            field=models.IntegerField(null=True),
        ),
    ]
