# Generated by Django 2.2 on 2020-04-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givebook', '0006_auto_20200331_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookadd',
            name='reqname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
